### ISSUE TITLE
ValueError: max() arg is an empty sequence；label的含义

### ISSUE THREAD

**Issue by Wang-Yufei** [Machine-Tom/bertsum-chinese-LAI#6]
您好！
我在训练的时候遇到了一个错误
Traceback (most recent call last):
  File "train_LAI.py", line 339, in <module>
    train(args, device_id)
  File "train_LAI.py", line 271, in train
    trainer.train(train_iter_fct, args.train_steps)
  File "E:\wyf\Projects\bertsum-chinese-LAI-master\src\models\trainer.py", line 142, in train
    for i, batch in enumerate(train_iter):
  File "E:\wyf\Projects\bertsum-chinese-LAI-master\src\models\data_loader.py", line 133, in __iter__
    for batch in self.cur_iter:
  File "E:\wyf\Projects\bertsum-chinese-LAI-master\src\models\data_loader.py", line 237, in __iter__
    batch = Batch(minibatch, self.device, self.is_test)
  File "E:\wyf\Projects\bertsum-chinese-LAI-master\src\models\data_loader.py", line 27, in __init__
    src = torch.tensor(self._pad(pre_src, 0))
  File "E:\wyf\Projects\bertsum-chinese-LAI-master\src\models\data_loader.py", line 14, in _pad
    width = max(len(d) for d in data)
ValueError: max() arg is an empty sequence
我试着运行了您给的例子中的数据，也出现了同样的错误，请问这是json到.pt时，数据没有正确的进行转换的原因，还是读取数据时发生的错误呢？
此外，data_builder_AI.py 中的labels 是句子的标签吗？因为我输出后发现，有些列表中只有一个1，但我的n_corps=2
感谢您的回复！

**Comment by tiexueYL** [comment]
我也出现这种错误了，你解决了吗

**Comment by Wang-Yufei** [comment]
没有解决，你想用这个模型的话，可以参考
https://github.com/425776024/bertsum-chinese

**Comment by zws123** [comment]
同样的问题+1

**Comment by Silent-Roar** [comment]
> 没有解决，你想用这个模型的话，可以参考 https://github.com/425776024/bertsum-chinese

你好，请问在参考这个新仓库时，训练之后如何根据不同的模型对生成的摘要进行rouge打分呢
